version: '3.3'

services:

  shop-php:
    container_name: shop-php
    user: "${UID}:${GID}"
    build:
      context: ./docker/dev/php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./:/var/www
      - ./docker/dev/php-fpm/php.ini:/usr/local/etc/php/php.ini

  shop-nginx:
    container_name: shop-nginx
    build:
      context: ./docker/dev/nginx
    volumes:
      - ./:/var/www
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/dev/nginx/sites/:/etc/nginx/sites-available
      - ./docker/dev/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - shop-php

    ports:
      - "80:80"
      - "443:443"

# shop-node:
#   container_name: shop-node
#   image: node:latest
#   volumes:
#     - ./:/var/www
#   working_dir: /var/www
#   ports:
#     - "8080:8080"

